"""Deterministic classification of every path in a snapshot.

Each path receives exactly one classification:

``parsed-candidate``
    A regular text blob in one of the four native languages (Rust, Scala, Python, Java),
    selected by file extension. Milestone 2 will attempt syntax extraction on these.
``text``
    Any other regular blob that was not excluded (documentation, configuration, build
    files, other languages). Milestone 2 indexes these lexically.
``excluded``
    Accounted for but not indexed, with exactly one ``reason`` and the ``rule`` that fired.

Rules are applied in this order; the first match wins:

1. ``submodule`` - a gitlink entry (mode 160000); it has no blob.
2. ``symlink``   - mode 120000. Links are recorded, never followed.
3. ``vendored``  - a directory segment is one of :data:`VENDORED_DIRS`.
4. ``generated`` - the file name matches :data:`GENERATED_SUFFIXES` or :data:`GENERATED_NAMES`.
5. ``oversize``  - the blob is larger than ``max_file_bytes``.
6. ``binary``    - a NUL byte occurs in the first ``binary_probe_bytes`` bytes (git's rule).
7. ``generated`` - the first ``marker_probe_bytes`` bytes contain a :data:`GENERATED_MARKERS`
   pattern.

Language is a guess from the file name alone (:func:`guess_language`); it is recorded for
every path, including excluded ones, and is ``None`` when unknown.
"""

from __future__ import annotations

import posixpath
import re
from dataclasses import asdict, dataclass

CLASSIFIER_VERSION = 1

PARSED_CANDIDATE = "parsed-candidate"
TEXT = "text"
EXCLUDED = "excluded"
CLASSIFICATIONS = (PARSED_CANDIDATE, TEXT, EXCLUDED)

REASONS = ("binary", "generated", "oversize", "submodule", "symlink", "vendored")

PARSED_LANGUAGES = frozenset({"java", "python", "rust", "scala"})

VENDORED_DIRS = frozenset(
    {"node_modules", "third-party", "third_party", "thirdparty", "vendor", "vendored"}
)

GENERATED_SUFFIXES = ("_pb2.py", "_pb2.pyi", "_pb2_grpc.py", ".pb.go", ".pb.h", ".pb.cc")

GENERATED_NAMES = frozenset(
    {
        "Cargo.lock",
        "Pipfile.lock",
        "package-lock.json",
        "pnpm-lock.yaml",
        "poetry.lock",
        "uv.lock",
        "yarn.lock",
    }
)

GENERATED_MARKERS: tuple[tuple[str, re.Pattern[bytes]], ...] = (
    ("@generated", re.compile(rb"@generated")),
    ("protoc", re.compile(rb"Generated by the protocol buffer compiler")),
    ("go-generated", re.compile(rb"Code generated .{0,200}DO NOT EDIT\.")),
)

_EXTENSIONS = {
    ".rs": "rust",
    ".scala": "scala",
    ".sc": "scala",
    ".py": "python",
    ".pyi": "python",
    ".java": "java",
    ".md": "markdown",
    ".rst": "restructuredtext",
    ".txt": "plain-text",
    ".toml": "toml",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".json": "json",
    ".ipynb": "jupyter-notebook",
    ".xml": "xml",
    ".ini": "ini",
    ".cfg": "ini",
    ".proto": "protobuf",
    ".thrift": "thrift",
    ".gql": "graphql",
    ".graphql": "graphql",
    ".bazel": "starlark",
    ".bzl": "starlark",
    ".sh": "shell",
    ".bash": "shell",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".c": "c",
    ".h": "c-header",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".cxx": "cpp",
    ".hh": "cpp",
    ".hpp": "cpp",
    ".hxx": "cpp",
    ".cu": "cuda",
    ".cuh": "cuda",
    ".go": "go",
    ".kt": "kotlin",
    ".sql": "sql",
    ".html": "html",
    ".css": "css",
}

_NAMES = {
    "BUILD": "starlark",
    "Cargo.lock": "toml",
    "poetry.lock": "toml",
    "uv.lock": "toml",
    "WORKSPACE": "starlark",
    "Dockerfile": "dockerfile",
    "Makefile": "make",
    ".gitignore": "gitignore",
}


@dataclass(frozen=True, slots=True)
class ClassifierConfig:
    max_file_bytes: int = 1_048_576
    binary_probe_bytes: int = 8000
    marker_probe_bytes: int = 2048

    @property
    def head_bytes(self) -> int:
        """How many leading bytes of each blob the rules need to see."""
        return max(self.binary_probe_bytes, self.marker_probe_bytes)

    def to_dict(self) -> dict[str, int]:
        return {"version": CLASSIFIER_VERSION, **asdict(self)}


@dataclass(frozen=True, slots=True)
class Classification:
    classification: str
    reason: str | None
    rule: str | None
    language: str | None


def guess_language(path: str) -> str | None:
    """Language guessed from the file name only (extension or well-known name)."""
    name = posixpath.basename(path)
    if name in _NAMES:
        return _NAMES[name]
    _, ext = posixpath.splitext(name)
    return _EXTENSIONS.get(ext.lower())


def classify(
    path: str,
    mode: str,
    obj_type: str,
    size: int | None,
    head: bytes,
    config: ClassifierConfig,
) -> Classification:
    """Apply the ordered rules from the module docstring to one tree entry."""
    language = guess_language(path)

    def excluded(reason: str, rule: str) -> Classification:
        return Classification(EXCLUDED, reason, rule, language)

    if obj_type == "commit" or mode == "160000":
        return excluded("submodule", "mode:160000")
    if mode == "120000":
        return excluded("symlink", "mode:120000")
    directories = path.split("/")[:-1]
    for segment in directories:
        if segment in VENDORED_DIRS:
            return excluded("vendored", f"dir:{segment}")
    name = posixpath.basename(path)
    if name in GENERATED_NAMES:
        return excluded("generated", f"name:{name}")
    for suffix in GENERATED_SUFFIXES:
        if name.endswith(suffix):
            return excluded("generated", f"suffix:{suffix}")
    if size is not None and size > config.max_file_bytes:
        return excluded("oversize", f"size>{config.max_file_bytes}")
    if b"\0" in head[: config.binary_probe_bytes]:
        return excluded("binary", f"nul-in-first-{config.binary_probe_bytes}-bytes")
    probe = head[: config.marker_probe_bytes]
    for marker_name, pattern in GENERATED_MARKERS:
        if pattern.search(probe):
            return excluded("generated", f"marker:{marker_name}")
    if language in PARSED_LANGUAGES:
        return Classification(PARSED_CANDIDATE, None, None, language)
    return Classification(TEXT, None, None, language)


_LICENSE_NAME = re.compile(
    r"(?i)(licen[cs]e|copying|notice|third[-_]?party[-_]?notices?)([-_.][a-z0-9]+)*"
)

LICENSE_HINTS: tuple[tuple[str, tuple[bytes, ...]], ...] = (
    ("Apache-2.0", (b"apache license", b"version 2.0")),
    ("MIT", (b"permission is hereby granted, free of charge",)),
    ("BSD-style", (b"redistribution and use in source and binary forms",)),
    ("GPL-family", (b"gnu general public license",)),
    ("LGPL-family", (b"gnu lesser general public license",)),
    ("AGPL-family", (b"gnu affero general public license",)),
    ("MPL-2.0", (b"mozilla public license", b"2.0")),
)

_SPDX = re.compile(rb"SPDX-License-Identifier:\s*([A-Za-z0-9.+ ()-]+)")


def license_kind(path: str) -> str | None:
    """``license``, ``copying``, ``notice`` or ``third-party-notices`` for license-like files."""
    name = posixpath.basename(path)
    match = _LICENSE_NAME.fullmatch(name)
    if not match:
        return None
    if guess_language(name) in PARSED_LANGUAGES:
        return None  # e.g. ``license.rs`` is source code, not a license file
    stem = match.group(1).lower()
    if stem.startswith("licen"):
        return "license"
    if stem.startswith("third"):
        return "third-party-notices"
    return stem


def license_hints(content: bytes) -> tuple[str, ...]:
    """Keyword hints about which licenses a file mentions. Not a license determination."""
    lowered = content.lower()
    hints = [name for name, needles in LICENSE_HINTS if all(n in lowered for n in needles)]
    for match in _SPDX.finditer(content):
        hints.append("spdx:" + match.group(1).decode("ascii").strip())
    return tuple(dict.fromkeys(hints))
